version: '3.8'

services:
  restaurante:
    build: .
    ports:
      - '5000:5000'
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=sua-chave-secreta-aqui
      - DATABASE_URL=sqlite:///app.db
    volumes:
      - ./backend/src/database:/app/src/database
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:5000/health']
      interval: 30s
      timeout: 10s
      retries: 3
